export const usStates = [
  { value: 'ALABAMA', label: 'AL' },
  { value: 'ALASKA', label: 'AK' },
  { value: 'AMERICAN SAMOA', label: 'AS' },
  { value: 'ARIZONA', label: 'AZ' },
  { value: 'ARKANSAS', label: 'AR' },
  { value: 'CALIFORNIA', label: 'CA' },
  { value: 'COLORADO', label: 'CO' },
  { value: 'CONNECTICUT', label: 'CT' },
  { value: 'DELAWARE', label: 'DE' },
  { value: 'DISTRICT OF COLUMBIA', label: 'DC' },
  { value: 'FEDERATED STATES OF MICRONESIA', label: 'FM' },
  { value: 'FLORIDA', label: 'FL' },
  { value: 'GEORGIA', label: 'GA' },
  { value: 'GUAM', label: 'GU' },
  { value: 'HAWAII', label: 'HI' },
  { value: 'IDAHO', label: 'ID' },
  { value: 'ILLINOIS', label: 'IL' },
  { value: 'INDIANA', label: 'IN' },
  { value: 'IOWA', label: 'IA' },
  { value: 'KANSAS', label: 'KS' },
  { value: 'KENTUCKY', label: 'KY' },
  { value: 'LOUISIANA', label: 'LA' },
  { value: 'MAINE', label: 'ME' },
  { value: 'MARSHALL ISLANDS', label: 'MH' },
  { value: 'MARYLAND', label: 'MD' },
  { value: 'MASSACHUSETTS', label: 'MA' },
  { value: 'MICHIGAN', label: 'MI' },
  { value: 'MINNESOTA', label: 'MN' },
  { value: 'MISSISSIPPI', label: 'MS' },
  { value: 'MISSOURI', label: 'MO' },
  { value: 'MONTANA', label: 'MT' },
  { value: 'NEBRASKA', label: 'NE' },
  { value: 'NEVADA', label: 'NV' },
  { value: 'NEW HAMPSHIRE', label: 'NH' },
  { value: 'NEW JERSEY', label: 'NJ' },
  { value: 'NEW MEXICO', label: 'NM' },
  { value: 'NEW YORK', label: 'NY' },
  { value: 'NORTH CAROLINA', label: 'NC' },
  { value: 'NORTH DAKOTA', label: 'ND' },
  { value: 'NORTHERN MARIANA ISLANDS', label: 'MP' },
  { value: 'OHIO', label: 'OH' },
  { value: 'OKLAHOMA', label: 'OK' },
  { value: 'OREGON', label: 'OR' },
  { value: 'PALAU', label: 'PW' },
  { value: 'PENNSYLVANIA', label: 'PA' },
  { value: 'PUERTO RICO', label: 'PR' },
  { value: 'RHODE ISLAND', label: 'RI' },
  { value: 'SOUTH CAROLINA', label: 'SC' },
  { value: 'SOUTH DAKOTA', label: 'SD' },
  { value: 'TENNESSEE', label: 'TN' },
  { value: 'TEXAS', label: 'TX' },
  { value: 'UTAH', label: 'UT' },
  { value: 'VERMONT', label: 'VT' },
  { value: 'VIRGIN ISLANDS', label: 'VI' },
  { value: 'VIRGINIA', label: 'VA' },
  { value: 'WASHINGTON', label: 'WA' },
  { value: 'WEST VIRGINIA', label: 'WV' },
  { value: 'WISCONSIN', label: 'WI' },
  { value: 'WYOMING', label: 'WY' },
]
